version: '3.8'

services:

  webui:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    restart: always
    ports:
      - 7860:7860
    depends_on:
      - llm-rag
    networks:
      - rag-network

  chromadb:
    image: chromadb/chroma:latest
    restart: always
    volumes:
      - ./chroma-data:/chroma/chroma
    ports:
      - 8000:8000
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  llm-rag:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    depends_on:
      - chromadb
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./hf-models:/root/.cache/huggingface
    ports:
      - 9000:9000
    # deploy: # NOTE: Uncomment this if you have gpu
      # resources:
      #   reservations:
      #     devices:
      #       - driver: nvidia
      #         count: 1
      #         capabilities: [gpu]
    restart: always
    networks:
      - rag-network

volumes:
  index_data:

networks:
  rag-network:
    driver: bridge
