version: '3.8'

services:
  init:
    build:
      context: ./
      dockerfile: backend/Dockerfile.dbinit
    container_name: init
    image: rag/init
    command: ["poetry", "run", "python", "-m", "backend.src.init_db"]
    depends_on:
      - chromadb
    networks:
      - rag-network

  webui:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    container_name: webui
    image: rag/webui
    restart: always
    ports:
      - 7860:7860
    depends_on:
      - llm-rag
    networks:
      - rag-network

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    restart: always
    volumes:
      - ./chroma-data:/chroma/chroma
    ports:
      - 8000:8000
    networks:
      - rag-network
    healthcheck:
      # https://cookbook.chromadb.dev/running/health-checks/#docker-compose
      test: [ "CMD", "/bin/bash", "-c", "cat < /dev/null > /dev/tcp/localhost/8000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  llm-rag:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    container_name: llm-rag
    image: rag/llm
    depends_on:
      - chromadb
    env_file:
      - .env
    volumes:
      - ./hf-models:/root/.cache/huggingface
    ports:
      - 9000:9000
    command: ["poetry", "run", "uvicorn", "backend.src.main:app", "--host", "0.0.0.0", "--port", "9000"]
    # deploy: # NOTE: Uncomment this if you have gpu
      # resources:
      #   reservations:
      #     devices:
      #       - driver: nvidia
      #         count: 1
      #         capabilities: [gpu]
    restart: always
    networks:
      - rag-network


networks:
  rag-network:
    driver: bridge
