apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
      - name: chromadb
        image: chromadb/chroma:0.4.25.dev145
        ports:
        - containerPort: 8000
        # volumeMounts:
        # - mountPath: /chroma/chroma
        #   name: chroma-data
        livenessProbe:
          exec:
            command: ["/bin/bash", "-c", "cat < /dev/null > /dev/tcp/localhost/8000"]
          initialDelaySeconds: 30
          periodSeconds: 30
      # volumes:
      # - name: chroma-data
        # hostPath:
        #   path: ./chroma-data
      dnsPolicy: "ClusterFirst"
      dnsConfig:
        nameservers:
          - 8.8.8.8
---
apiVersion: v1
kind: Service
metadata:
  name: chromadb
spec:
  type: ClusterIP   # NodePort  # Добавлено
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    # nodePort: 30000  # Порт на хосте (опционально, иначе выберется автоматически)
  selector:
    app: chromadb



# kubectl port-forward service/chromadb 8000:8000
