apiVersion: apps/v1
kind: Deployment
metadata:
  name: init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init
  template:
    metadata:
      labels:
        app: init
    spec:
      containers:
      - name: init
        image: rag
        command: ["poetry", "run", "python", "-m", "backend.src.init_db"]
        # restartPolicy: Never
        imagePullPolicy: Never
      dnsPolicy: "ClusterFirst"
      dnsConfig:
        nameservers:
          - 8.8.8.8




# docker build -t rag/init -f backend/Dockerfile.dbinit .