apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: webui
        image: webui
        ports:
        - containerPort: 7860
        # restartPolicy: Always
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: webui
spec:
  ports:
  - port: 7860
    targetPort: 7860
  selector:
    app: webui
