apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
      - name: chromadb
        image: chromadb/chroma:0.4.25.dev145
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /chroma/chroma  # Путь внутри контейнера, куда будет смонтирована директория
          name: chroma-data         # Имя тома, который мы монтируем
        readinessProbe:
          httpGet:
            path: /docs  # Путь для проверки состояния сервиса
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          exec:
            command: ["/bin/bash", "-c", "cat < /dev/null > /dev/tcp/localhost/8000"]
          initialDelaySeconds: 30
          periodSeconds: 30
      volumes:
      - name: chroma-data
        persistentVolumeClaim:
          claimName: chroma-pvc
      dnsPolicy: "ClusterFirst"
      dnsConfig:
        nameservers:
          - 8.8.8.8
---
apiVersion: v1
kind: Service
metadata:
  name: chromadb
spec:
  type: ClusterIP   # NodePort  # Если нужно, можно заменить на NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: chromadb
