apiVersion: batch/v1
kind: Job
metadata:
  name: init-job
spec:
  template:
    metadata:
      labels:
        app: init
    spec:
      containers:
      - name: init
        image: rag
        command: ["poetry", "run", "python", "-m", "backend.src.init_db"]
        imagePullPolicy: Never
      restartPolicy: Never
      dnsPolicy: "ClusterFirst"
      dnsConfig:
        nameservers:
          - 8.8.8.8
  backoffLimit: 2  # Количество повторных запусков в случае сбоя




# docker build -t rag/init -f backend/Dockerfile.dbinit .